apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ffgtsqgmg-go 
  janus-idp.io/tekton: ffgtsqgmg-go
  backstage.io/kubernetes-id: ffgtsqgmg-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ffgtsqgmg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml